services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - app-network

  api:
    build:
      context: /
    depends_on:
      - redis
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: redis
      DB_PORT: 6379
    

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge